### PR TITLE
fix(plugin-grid): schema-aware multi-value semantics for bulk-edit params

### LINKED ISSUE #2204: BulkActionDialog params are schema-blind: a multi-value field param without explicit multiple:true renders single-select and patches a scalar
## 问题

批量编辑对话框的参数控件形态与写入 patch **完全不参照目标对象 schema**,单/多值语义只取决于 `BulkActionParam.multiple` 这个手写标志:

- `packages/plugin-grid/src/components/BulkActionDialog.tsx:475-497`(select)与 `:498-525`(lookup):`param.multiple ? <MultiSelectControl/> : <Select/>`——只看 param 声明,不看 grid 已持有的对象 schema 里目标字段是否为多值(multiselect/tags/checkboxes/lookup multiple)。
- `packages/plugin-grid/src/hooks/useBulkExecutor.ts:136-139`:
  ```ts
  const buildPatch = (): Record<string, unknown> => ({ ...(def.patch ?? {}), ...params });
  ```
  参数值原样进 patch,没有任何 schema 对照/归一化。

**后果**:视图作者给多值字段定义批量参数时漏写 `multiple: true`(极易发生,#2185 的 showcase 早期版本就踩过),UI 渲染成单选、patch 写出标量。在 framework objectstack-ai/framework#2552 落地之前,标量会被服务端原样落库,**静默写坏整列多值数据**(实测 PATCH `{"labels":"frontend"}` 返回 200 并按标量存储);#2552 之后服务端会兜底包装成单元素数组,但 UI 仍然把多值字段呈现为"只能选一个",语义错误依旧。

## 建议修复

1. BulkActionDialog 拿到 grid 的对象 schema 后,对 `operation: 'update'` 的参数按 `param.name` 对应的目标字段推导 `multiple`(param 显式声明优先,未声明时回退 schema:`multiselect`/`checkboxes`/`tags`/`select|lookup + multiple` → 多值)。
2. `buildPatch` 在合并 params 时按 schema 做形状归一化:目标字段为多值而值是标量 → 包装数组(与服务端 #2552 行为一致,双保险)。

### PR DESCRIPTION
**Pull request by baozhoutao**
Closes #2204

## Problem

BulkActionDialog was **schema-blind**: whether a bulk-edit param rendered a single- or multi-select — and whether the patch shipped a scalar or an array — depended solely on the hand-written `BulkActionParam.multiple` flag. A view author targeting a multi-value field (`multiselect`, `tags`, `checkboxes`, or `select`/`lookup`/`user`/`file`/`image` with `multiple: true`) who forgot the flag got:

1. a **single-select control** (user can only pick one value), and
2. a **scalar patch** (`{labels: "frontend"}`) written to an array-shaped column — silently corrupting data server-side.

## Fix

- **ObjectGrid** passes its `objectSchema.fields` (already held in state from server meta) into `BulkActionDialog` → `useBulkExecutor`.
- **BulkActionDialog**: explicit `param.multiple` (boolean) still wins; otherwise `update` params derive multi-ness from the target field definition via the new `isMultiValueField` helper — same semantics as the server-side guard in framework #2552 (always-multi: `multiselect`/`checkboxes`/`tags`; multi-capable with `multiple: true`: `select`/`radio`/`lookup`/`user`/`file`/`image`).
- **useBulkExecutor** shape-normalizes every outgoing patch (`run` **and** `retry`) with `normalizeMultiValuePatch`: a lone scalar aimed at a multi-value field is wrapped into a single-element array (copy-on-write, arrays/null pass through, no-op without a schema).

## Testing

- `packages/plugin-grid` vitest: **181/181 pass** including the new `bulkActionSchemaMultiple.test.tsx` (helper unit tests; schema-fallback renders multi-select + array patch; single-value non-regression; explicit `multiple: false` wins the UI but the executor still ships an array; scalar `def.patch` normalization; retry re-sends the normalized patch).
- `turbo run build --filter=@object-ui/plugin-grid` (incl. dts): 12/12 tasks pass.
- **Live end-to-end** (HMR console against a real objectstack dev server): a bulk action whose param *omits* `multiple` but targets a `multiselect` field now renders the multi-select control (badges + searchable checklist), and the record persists `["frontend","design"]` (verified via REST API) instead of a scalar.

Server-side counterpart: objectstack-ai/framework#2553 (defense-in-depth — engine wraps stray scalars on write).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by baozhoutao** [comment]
The **Test** failure here is a pre-existing `main` breakage, not from this PR: all 16 failures are in `app-shell/…/ObjectFieldInspector.test.tsx` (`client.listDrafts is not a function`), broken on `main` since #2199 landed (every `main` push CI run after 28682411708 is red with the same 16 failures). Fix: #2207. Will update this branch once that merges.
