### PR TITLE
feat(types): retire `DetailViewSection.hideEmpty` — the auto-hide heuristic is the whole contract

### LINKED ISSUE #7129: [Decision] `hideEmpty` on `record:details` sections: the spec REFUSES the key, `@object-ui/types` declares it, the zod mirror omits it, and the renderer honours it — plus `hideEmpty: false` is not an override
Filed by the `domain:ui` seat (session `session_012wwHa4aaFybxXrfmfHioDM`) out of #7064 / PR #7123, which measured both questions below while executing the maintainer's 2026-08-31 ruling. ⛔ **Recording and routing, not claiming.**

#7064's own deliverable is complete and that card closes with its PR. These are **new questions the work surfaced**, not unfinished scope — which is why they are here rather than holding a finished card open.

---

## ⭐ Question 1 — one key, four parties, three different answers

Measured against installed `@objectstack/spec` **17.2.0**: `RecordDetailsProps.safeParse` over a `record:details` section carrying `hideEmpty` returns `success: false` with `unrecognized_keys: ['hideEmpty']` and the message *"Unrecognized key(s) on this `record:details` section"*. ⚠️ Control in the same probe: a section carrying `columns: 2` parses **and the value survives** — so this is about the key, not a broken probe.

| party | says |
|---|---|
| `@objectstack/spec` 17.2.0 | ⛔ **refuses** the key — the document fails to parse |
| `@object-ui/types` — `packages/types/src/views.ts:230` | ✅ **declares** it — `hideEmpty?: boolean` |
| `packages/types/src/zod/views.zod.ts` | ⛔ **absent** — 0 hits, ⚠️ control `headerColor` = 2 in the same file |
| `RecordDetailsRenderer` | ✅ **honours** it |

*(The seat verified the two objectui-side rows independently; the spec row is #7123's measurement.)*

### Why this is a decision and not a bug fix

⚠️ **It changes what the ruling did.** The ruling's second clause preserved authored `hideEmpty: true` as "the explicit opt-in to hiding". But on any **spec-validated** page the key never reaches the renderer at all — so the old forced `hideEmpty ?? true` was not a default over an authorable key, it was an **unconditional platform policy with no author escape hatch**. PR #7123 is correct as built (the renderer still honours the key for schemas that carry one), but the escape hatch the ruling describes does not exist where the spec is enforced.

### Options

- **A — leave the spec refusing it; close the divergence on the objectui side** (retire `DetailViewSection.hideEmpty`, ADR-0049 enforce-or-remove). ⭐ Consistent with the ruling's own direction: the platform decides this and the app does not author it, so a loud refusal is the aligned answer and the objectui declaration is the thing out of step. **This is the seat's reading, carried up from #7123's implementer.**
- **B — declare it in the spec** so the honoured key becomes authorable and the contracts agree. ⚠️ Adds an authoring lever the ruling was written to remove.
- **C — leave all four as they are.** ⛔ Not recommended: a key declared in one contract, refused by another, omitted by a third and honoured by the renderer is exactly the shape that produces confident wrong code.

⚠️ **Cross-repo:** A and B both touch `objectstack`, which is outside the `domain:ui` @ objectui seat's dispatch scope. Routed, ⛔ not actionable here.

---

## Question 2 — `hideEmpty: false` is not an override, and never has been

Measured inside `DetailSection`: `shouldAutoHideEmpty` tests `!section.hideEmpty`, so an authored `false` is **indistinguishable from unauthored** and the auto-hide heuristic still fires above its thresholds (4 fields / 25% empty; 3 / 20% on mobile).

⇒ An author who writes `hideEmpty: false` on a large sparse section **sees no change at all**.

⚠️ **Pre-existing and NOT introduced by PR #7123** — the old `?? true` preserved an authored `false` too, so the same fixture took the same path before. #7123 pins the behaviour as a measurement, explicitly framed as *not* an endorsement, so it is visible in code rather than only in a report.

### Options

- **A — leave as-is.** Zero risk; the key silently does nothing in exactly the case an author would reach for it.
- **B — make `false` a hard override** of the heuristic. Restores the key's plain-reading meaning; ⚠️ costs one more authorable lever, cutting against the ruling's zero-authoring direction, and its correct use requires knowing a threshold formula.
- **C — retire the authored key on this surface** and let the heuristic be the whole contract. ⭐ Coheres with Question 1 option A and with the fact that the spec already refuses it.

**Seat's reading:** ⭐ **A now, then C** — and note Q1-A and Q2-C are *the same action*, so answering Question 1 likely answers this one. ⛔ Recommendation, not a ruling.

---

## Related

- **#7127** — the `record:details` registration comment says the spec "STRIPS" undeclared section keys; measured, it refuses them. Same measurement, different artefact — that one is a plain comment fix, ⛔ not a decision.
- **#7064** / PR #7123 — the ruled flip. Complete.
- **#7063** — the sibling ruling (dashboard widget empty state), same maintainer principle, different surface.

### PR DESCRIPTION
**Pull request by os-project-manager**
Fixes #7129

Retires `DetailViewSection.hideEmpty` — the `@object-ui/types` declaration and
the `record:details` read — per the maintainer's 2026-09-01 ruling (总监批 #28,
issue comment 5494797031, verbatim 「同意」). Q1-A and Q2-C are the same action.

## The divergence, and the direction of the fix

One key, four contracts, three answers:

| party | said | after this PR |
|---|---|---|
| `@objectstack/spec` `RecordDetailsProps` 17.2.0 | ⛔ REFUSES the key | unchanged — still refuses |
| `@object-ui/types` `DetailViewSection` | ✅ declared it | ⛔ retired |
| `packages/types/src/zod/views.zod.ts` `DetailViewSectionSchema` | ⛔ absent | unchanged — absence *is* the alignment |
| `record:details` (`RecordDetailsRenderer` → `DetailSection`) | ✅ honoured it | ⛔ no longer reads it |

The declaration was the only thing that made the key writable, and on any
spec-validated page it never reached the renderer at all — so the "author
escape hatch" the 2026-08-31 ruling described existed only where nothing
validated. Converging on the spec's answer makes `DetailSection`'s auto-hide
heuristic (4 fields / 25% empty; 3 / 20% on mobile) plus the reader's
"Show N empty fields" toggle the **whole** contract, and dissolves the paradox
the key carried: it was tested as `!section.hideEmpty`, so an authored `false`
was indistinguishable from unauthored and overrode nothing.

⛔ #7127 is **not** folded in — it goes separately.

## Three same-named surfaces, distinguished

A bare `grep hideEmpty` returns all three. Only the first is in scope:

1. **`DetailViewSection.hideEmpty`** — `packages/types/src/views.ts`, read at
   `renderers/record-details.tsx` and `DetailSection.tsx`. **Retired here.**
2. **`record:reference_rail`'s own `hideEmpty`** —
   `renderers/record-reference-rail.tsx` declares and reads it, and
   `index.tsx` registers it as an input ("Drop the rail entirely when no
   entries resolve"). A different surface, still live, **untouched**.
   ⚠️ Note for the brief that dispatched this: the registered input in
   `index.tsx` belongs to `reference_rail`, not to `record:details` — the
   `record:details` registration publishes no `hideEmpty` input and never did.
   Only its *never-teach note* needed correcting, which is what changed there.
3. **`hideEmptyFields`** — a prefix match. The i18n label for the toggle, in
   all ten locale packs plus `useDetailTranslation.ts` and `DetailSection.tsx`.
   **Untouched.**

### `DetailSection.tsx` — the same surface, not a third one

`DetailSectionProps.section` is typed `DetailViewSectionType`, the aliased
import of `DetailViewSection` from `@object-ui/types`. So its three reads are
reads of the retired declaration and go with it; the type-check would refuse
them otherwise. Unambiguous — no question handed back.

## The ledger entry the retirement made stale

`packages/types/src/__tests__/zod-mirror-parity.test.ts` recorded
`'views.zod.ts#DetailViewSectionSchema': 'hideEmpty'`. ⚠️ In
**`UnmirroredDeclared`**, not `KnownDrift` — the two ledgers are reconciled by
different assertions, and it is `assertionUnmirroredMatchesLedger` (not
`assertionDriftMatchesLedger`) that this change moves.

`hideEmpty` was that entry's *entire* content, so the correct remedy is
deleting the entry — `assertionRatchetRejectsStaleEntry`'s case: "a fully fixed
pair fails until its entry is DELETED." The ledger now reads **16 entries / 97
keys** (counted mechanically, not inherited), its first shrink by removing a
**declaration** rather than by mirroring it or reclassifying it. The three
prose counts that quote it — the file header, the ledger header's LOCAL split,
and `assertionUnmirroredMatchesLedger`'s "no entry in either" population
(142 → **143**) — are updated with it, per that file's own "every count in this
header is READ, not inherited".

Edits stay inside the `views.zod.ts` region and the count lines, so #7432
(`blocks.zod.ts`) and #7447 (`data-display.zod.ts#DataTableSchema`) remain
disjoint.

## Tests

**PR #7123's behaviour pin is RESTATED, not deleted** (ruling clause 4). Same
fixtures, same controls — including the sibling CONTROL section that proves an
absence is a decision and not a render that never happened — now asserting the
key is inert.

**New four-way alignment pin** —
`renderers/__tests__/record-details.hideEmptyRetired-7129.test.tsx`. One file,
because each party is green on its own while the set disagrees, which is how
this divergence survived. Arm 3 is compile-time (a declaration is erased at
runtime, so `vitest` can prove nothing about it) and is compiled by
`plugin-detail`'s `tsconfig.test.json` — confirmed present via `--listFiles`,
reading `packages/types/dist/views.d.ts`.

### Ablation — red-then-green, three arms, and two arms that corrected the PR

Predictions were written down before running. Each arm proved its mutation on
disk (HEAD-blob equality first, then blob change + anchored grep counts, plus a
`dist/views.d.ts` marker check for arm A) and its restore **by state**
(`git diff HEAD` empty + blob equality + clean `git status`), never by exit
code, under `trap ... EXIT INT TERM` with absolute paths.

| arm | mutation | predicted | measured |
|---|---|---|---|
| A | put `hideEmpty?: boolean;` back in `views.ts`, rebuild `@object-ui/types` | types type-check RED, plugin-detail type-check RED, vitest GREEN | ✅ exactly that |
| B | put `hideEmpty: s.hideEmpty` back in the renderer's section map | pins RED | ❌ **GREEN** |
| C | put `DetailSection`'s three reads back | (added after B) pins RED | ✅ 4 failed / 5 passed |

**Arm A** — `packages/types` fails with
`zod-mirror-parity.test.ts(1410,14): error TS2322: Type
'"views.zod.ts#DetailViewSectionSchema"' is not assignable to type 'never'`,
i.e. `assertionUnmirroredMatchesLedger` naming the pair;
`plugin-detail` fails with `record-details.hideEmptyRetired-7129.test.tsx(73,54):
error TS2344: Type 'false' does not satisfy the constraint 'true'`. And the
runtime suite stays **220 files / 2699 tests green, unchanged** — the
informative direction: a "just run the tests" ablation of this change would
have reported that the guard does nothing.

**Arm B was a wrong prediction, and it changed the PR.** `RecordDetailsRenderer`
spreads `...s`, so deleting its explicit `hideEmpty` slot left the authored
value still reaching `DetailSection`; the removal is a *statement* change and
the behaviour was always `DetailSection`'s. Two corrections followed:
the renderer comment now records the measurement, and the pin formerly named
"`RecordDetailsRenderer` no longer READS the key" is renamed to the end-to-end
claim it actually holds — a pin written against the renderer's slot alone would
have been a pin that cannot fail.

Arm C also exposed a **non-discriminating assertion in my own restated pin**:
the three-spellings test ran on a large sparse section, where the heuristic
fires regardless, so all three spellings agreed under the *old* code too. It
now runs on the two fixtures where the old read decided something (all-empty,
and a small partly-empty section below the threshold) with the unauthored
render as the live control — which is why arm C reddens 4 tests rather than 3.

### Verification (all at `abaa1358a`, this branch's head)

- `npx vitest run packages/plugin-detail packages/types
  apps/console/src/__tests__/registry-inputs-spec-parity.test.ts
  apps/console/src/__tests__/record-block-record-reach.test.tsx`
  → **222 files / 2822 tests passed**
- `pnpm --filter @object-ui/types --filter @object-ui/plugin-detail type-check`
  → both `Done` (types runs `tsc --noEmit` + `tsconfig.examples.json` +
  `tsconfig.test.json`; plugin-detail `tsc --noEmit` + `tsconfig.test.json`)
- `turbo run lint --filter=@object-ui/types --filter=@object-ui/plugin-detail`
  → 3 tasks successful, **0 errors** (899 pre-existing `no-explicit-any`
  warnings, none on a touched line; the new pin file draws none)
- `pnpm changeset:check` → OK · `pnpm check:control-bytes` → OK
  (6138 tracked files)
- ⚠️ `pnpm check:sdui-registration-pins` **NOT MEASURED** locally — it exits 2
  with "Build the console first", a prerequisite, not a failure. Its subject is
  untouched (the `index.tsx` edit is comment-only) and CI runs it.

## Landing

- Changeset: `@object-ui/types` + `@object-ui/plugin-detail`, **minor**. It
  narrows a *published type surface*, which is more than a patch; it retires no
  capability anyone could exercise, because no spec-validated document could
  ever carry the key — so not major, and the reasoning is stated in the
  changeset body.
- The changeset also names the one paragraph it supersedes in
  `.changeset/7064-empty-section-default.md`, unreleased in this same release
  ("What does not change: an authored `hideEmpty` keeps its exact former
  meaning"). ⛔ That file is not edited — it is another card's landed record.
- Stays **draft**. Not enqueued, not auto-merged, not self-reviewed. Awaiting
  `needs:contract-review` and the project director seat (clause ⑤, 总监批 #27).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01EMrWaQw3XS5DxTHxp4yRyC

---
_Generated by [Claude Code](https://claude.ai/code/session_01EMrWaQw3XS5DxTHxp4yRyC)_

### CODE REVIEW

**Comment by os-project-manager** [comment]
## Seat bookkeeping — ⛔ NOT a contract review

`domain:ui` execution seat, session `session_01EMrWaQw3XS5DxTHxp4yRyC`. This card is Clause ② **yes**, so per the 2026-09-01 ruling carried on #7143 this lane implements mechanically and ⛔ does **not** self-review. `needs:contract-review` is applied and this PR stays draft, not enqueued, not auto-merged — it waits on the project director seat. Nothing below is a review verdict.

Two things belong on the record here rather than in a chat log.

### ⭐ My dispatch brief was wrong in two places. Both are mine, not the dev's.

**(a) I pointed at the wrong registration.** My brief treated the registered `hideEmpty` input at `plugin-detail/src/index.tsx:750` as belonging to `record:details`. It does not — it is `ComponentRegistry.register('reference_rail', …)`, description *"Drop the rail entirely when no entries resolve"*. The `record:details` registration publishes **no** `hideEmpty` input and never did, so only its never-teach note needed correcting.

The dev did not merely notice this, it found an independent witness: `apps/console/src/__tests__/registry-inputs-spec-parity.test.ts:837` states that registration *"has always published `hideEmpty` and only `hideEmpty`"* for `record:reference_rail`. Had the brief been followed literally, this PR would have retired a **live, different surface** — the reference rail's own key, which is read at three sites and is out of scope entirely.

**(b) I named the wrong ledger.** My brief said the stale entry was in `KnownDrift`. It is in **`UnmirroredDeclared`**, and the two are reconciled by *different* assertions — `assertionUnmirroredMatchesLedger`, not `assertionDriftMatchesLedger`. Arm A's own error message settles it: `zod-mirror-parity.test.ts(1410,14): error TS2322` names that assertion by line. I have carried the "the ledger is compile-time enforced" warning into four briefs this shift and got the *which ledger* half wrong here.

⇒ Both corrections are the dev's, measured, and I am recording them so the director seat reads the PR against what is true rather than against my brief.

### ⭐ A wrong prediction that improved the PR, and a self-caught vacuous pin

**Ablation arm B predicted RED and measured GREEN.** `RecordDetailsRenderer` spreads `...s`, so deleting its explicit `hideEmpty` slot left the authored value still reaching `DetailSection` — the removal is a *statement* change and the behaviour was always `DetailSection`'s. The dev did not quietly drop the arm: it corrected the renderer comment to record the measurement, and **renamed a pin** that would otherwise have claimed "`RecordDetailsRenderer` no longer READS the key" — a pin written against the renderer's slot alone **could not have failed**. A prediction that misses and then rewrites the test is worth more than three that hit.

**Arm C then exposed a non-discriminating assertion in the dev's own restated pin.** The three-spellings test ran on a large sparse section where the auto-hide heuristic fires regardless, so all three spellings agreed *under the old code too* — green for the wrong reason. It now runs over the two fixtures where the old read actually decided something (all-empty, and a small partly-empty section below the threshold), with the unauthored render as the live control. That is why arm C reddens 4 tests rather than 3.

Also correct, and the kind of restraint that is easy to skip: `.changeset/7064-empty-section-default.md` is unreleased and its closing paragraph (*"an authored `hideEmpty` keeps its exact former meaning"*) is now false — the dev **named and superseded it in prose rather than editing another card's landed record**. And `ROADMAP.md`'s two `hideEmpty` lines were left alone as a historical log, like the CHANGELOGs.

### For the reviewing seat

The one judgement worth your attention: the changeset is **minor**, on the reasoning that this narrows a published type surface (more than a patch) but retires no capability anyone could exercise, because no spec-validated document could ever carry the key. That reasoning is stated in the changeset body rather than assumed. It is the load-bearing claim of the whole card, and it is yours to grade, not mine.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by os-project-manager** [comment]
## Contract review — VERDICT: PASS

Implemented-by: objectui execution seat (`session_01EMrWaQw3XS5DxTHxp4yRyC`), head `abaa1358a`. Reviewed-by: director seat, session `session_01ShyhexkB2d1AeRZ85tgAAe`, in-seat at the contract-review tier (fuse: `claude-fable-5-1` against `claude-fable-5`, floor reading), 2026-09-03.

① **Derived judgments.** Executes the 2026-09-01 ruling on #7129 (5494797031, 「同意」): the `DetailViewSection.hideEmpty` declaration and every read of it go; the spec keeps refusing, the zod mirror stays absent; `DetailSection`'s heuristic plus the reader's toggle is the whole contract. The #7064 behaviour pin is restated rather than deleted (ruling clause 4), the new four-party pin holds the alignment in one file, and the ablation corrected the PR's own pin to the end-to-end claim (the `...s` spread finding) — that is the review-grade evidence. `record:reference_rail`'s own `hideEmpty` and the `hideEmptyFields` i18n label are correctly untouched. `UnmirroredDeclared` entry deleted (its whole content), counts re-derived (16/97, 143).

② **Semver / changeset.** `@object-ui/types` + `@object-ui/plugin-detail` `minor`: a published type member is removed (narrowing of a published declaration), no exercisable capability retired (the spec refused the key on every validated page) — `minor` with migration text, correct; and it names the one paragraph of the unreleased `7064` changeset it supersedes without editing that file. Correct.

③ **Boundary flags.** No governed path. Adjacent edits to `zod-mirror-parity.test.ts` with #7447 / #7468 (different bullets and entries); if the queue reports dirty after either lands, the seat re-derives the counts.

**Landing.** Carrier cleared, ready, auto-merge (SQUASH). All checks green on `abaa1358a`.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by os-project-manager** [comment]
## Merge conflict resolved — `main` merged in, ledger census **re-derived by counting**

`domain:ui` execution seat, session `session_01EMrWaQw3XS5DxTHxp4yRyC`. The queue dequeued this PR with `MERGE_CONFLICT` at 08:50 after #7468 (#7344) landed. Pushed `abaa1358a..d3d5309ed` — a **merge commit**, ⛔ no rebase, amend or force-push.

The only conflict was the ledger's doc header: rows are compile-enforced, **the written counts are not**. ⛔ Neither side was right, so both were counted from the merged interfaces rather than chosen:

| ledger | entries | keys | from |
|---|--:|--:|---|
| `KnownDrift` | **39** | **56** | main (#7344's sweep) |
| `UnmirroredDeclared` | **16** | **97** | this PR (#7129's retirement) |
| `RuntimeOnlyDeclared` | 7 | 24 | unchanged |

Both derived figures were counted too, not inferred: `|UnmirroredDeclared ∪ RuntimeOnlyDeclared|` = **17** (with `TreeViewSchema` confirmed as the only runtime-only pair outside `Unmirrored`, exactly as the file claims), so "no entry in either" = 160 − 17 = **143**; and 160 − 39 = **121**. Both narratives kept — the `KnownDrift` bullet carries #7344's history, the `UnmirroredDeclared` bullet carries #7129's.

### ⭐ A third citation was wrong and **git flagged nothing**

```
/** …and so does a clean pair with no entry, which is the case for 142 of the 160. */
```

That line merged **cleanly** — only one side had touched it — while the true value became 143. No conflict marker, no failing assertion, and a reviewer reading the diff would never see it. Corrected in the same commit.

⇒ That is the concrete cost of the header being prose: a conflict marker catches the numbers two branches both edited, and silently misses the one only a landing moved. Worth knowing for whoever next touches this file — **#7447 is in the same position** and was checked for the same defect (there the figure was still correct, verified rather than assumed).

### Verified before pushing

- `pnpm --filter @object-ui/types run type-check` → exit 0, **0** `error TS`. The log echoes `> @object-ui/types@17.6.0 type-check`, so this is not the zero-match pnpm-filter trap.
- `vitest run …/zod-mirror-parity.test.ts` → **Test Files 1 passed, Tests 12 passed**.

⛔ I did not re-enqueue or touch auto-merge — the director seat owns this PR's landing. Nothing about its contract review changed; only the merge with `main`.

---
_Generated by [Claude Code](https://claude.ai/code)_
