### PR TITLE
console: read the converged FormFieldSpec instead of a third copy of it

### LINKED ISSUE #5542: [finding] A THIRD inline copy of the form-field authoring contract lives in apps/console FormPage.tsx — objectui#5040 converged only the app-shell two
Found while implementing #5040 (PR #5537). Filed unassigned, for PM triage — not
worked on here: `apps/console` was outside that card's declared file surface and
is held by in-flight #5504.

## Mechanism

#5040 is written around **two** inline descriptions of one contract — the
metadata-admin form field authoring type — converging into one. Measured, there
are **three**:

| # | site | status |
| --- | --- | --- |
| 1 | `packages/app-shell/src/views/metadata-admin/SchemaForm.tsx` — `FormFieldSpec` | converged by PR #5537 into the leaf `views/metadata-admin/form-spec.ts` |
| 2 | `packages/app-shell/src/views/metadata-admin/widgets.tsx` — `WidgetProps.fieldSpec` | converged by PR #5537; now *is* `FormFieldSpec` |
| 3 | `apps/console/src/components/FormPage.tsx:278` — `interface FormFieldSpec` | **untouched** — a third independent declaration under the same name |

Site 3 declares its own `interface FormFieldSpec`, used at `:275`
(`fields: Array<string \| FormFieldSpec>`) and `:352` (`const override:
FormFieldSpec = …`). It is a separate, hand-written description of the same
authoring shape, under the same name, in a different package.

## Why this is worth a card rather than a shrug

The defect #5040 recorded was not that a key was missing — it was that **two
descriptions of one contract drifted**, and nothing could notice because each
was only ever checked against itself. PR #5537 removed one of the two seams. A
third declaration under the same name leaves the same failure mode available:
site 3 can drift from the app-shell surface exactly as site 2 did, and the
symptom would again be "the type rejects the configuration the runtime accepts",
which no runtime test can see.

Note site 3 was NOT the source of the `dependsOn` defect and does not have to
adopt the app-shell type as-is — whether these are one contract or two layers
(`apps/console` may legitimately author a narrower shape) is exactly the
question triage should settle, and the answer might be "declare them distinct
and rename one", not "merge".

## Severity note

Filed as an observation (`finding`, no `pm:queue`): there is no user-reachable
failure today. Recording it because the shape — one contract, several
independent descriptions — is the class this repo has repeatedly paid for, and
because a card written around "two copies" would read as complete while a third
stayed open. Severity is triage's call, not mine at filing time.

## Boundary

- Searched open issues before filing (`FormFieldSpec` / `FormPage.tsx` /
  console-duplicate phrasings) — no card covers site 3.
- Not a duplicate of #5040: that card's declared surface was
  `packages/app-shell/src/views/metadata-admin/**`, and it is landing the
  app-shell half only, which PR #5537 states in its scope section.
- #5504 is untouched by this report; it is named only because it currently holds
  `apps/console`.

---
_Generated by [Claude Code](https://claude.ai/code/session_014zHsbJoTkTZeJQ5DLbRXrE)_

---
_Generated by [Claude Code](https://claude.ai/code)_

### PR DESCRIPTION
**Pull request by os-sales**
Fixes #5542

## The comparison, key by key — the route is a measurement

Triage ruled that both outcomes close the class and that which one applies is a
measurement, not a preference. Here is the measurement.

The console's declaration (`FormPage.tsx:278` on `cad512fe1`) had **9 keys**. The
converged app-shell declaration (`form-spec.ts:26`) has **26**. Every one of the
console's 9 is present in the shared type with an **identical** type, and the console
had **zero** keys of its own:

| key | console | app-shell `form-spec.ts` | verdict |
| --- | --- | --- | --- |
| `field` | `string` (required) | `string` (required) | identical |
| `label` | `string?` | `string?` | identical |
| `placeholder` | `string?` | `string?` | identical |
| `helpText` | `string?` | `string?` | identical |
| `required` | `boolean?` | `boolean?` | identical |
| `readonly` | `boolean?` | `boolean?` | identical |
| `hidden` | `boolean?` | `boolean?` | identical |
| `colSpan` | `1 \| 2 \| 3 \| 4` optional | `1 \| 2 \| 3 \| 4` optional | identical |
| `widget` | `string?` | `string?` | identical |
| `type`, `options`, `reference`, `dependsOn`, `maxLength`, `minLength`, `min`, `max`, `precision`, `scale`, `multiple`, `immutable`, `disclosure`, `language`, `visibleWhen`, `visibleOn`, `fields` | absent | declared | **17 keys the console did not admit** |

Zero disagreements, zero console-only keys, strict 9-of-26 subset.

## Which route the comparison supports, and why

**Same contract — import it.** A subset relation alone does not settle it; a narrower
authoring layer would also look like a subset. Three further facts do settle it:

1. **The position describes an authored document, not something the console authors.**
   The type sits on `FormSectionSpec.fields`, and `sec.fields` is read straight off the
   `/meta/view/:name` payload (`resolveInternalForm` casts the response into
   `FormViewSpec`). That is the same spec `FormView` metadata-admin renders — app-shell's
   own container says so in as many words, "Lightweight shape of the spec `FormView` we
   consume". Both files even spell the same character-identical six-member `type` union
   and both call the element type `FormFieldSpec`.
2. **The narrower renderer type already exists, under a different name.** `FormPage.tsx`
   declares `RenderableField` — the normalized row `buildSections` emits, which really is
   "what this renderer honours". The narrowing role was already filled, so the local
   `FormFieldSpec` was not filling it.
3. **So the console's copy was not a narrower layer, it was a wrong description.** Legal
   metadata the spec accepts and the runtime passes through — `visibleWhen`, `dependsOn`,
   `type`, `options`, `immutable`, the recursive `fields`, 17 keys in all — was
   undeclared here. That is objectui#5040's own symptom, "the type rejects the
   configuration the runtime accepts", which no runtime test can see.

A rename would have declared a narrowing that the code does not perform, so it was not
the honest route even though it is the smaller diff.

## The change

- `@object-ui/app-shell` re-exports `FormFieldSpec` from its package root. **Type-only**
  — erased at build, nothing added to the bundle (the eager-closure gate confirms it
  below). Reachability is the load-bearing half of the fix: the type was previously
  unnameable outside `views/metadata-admin/`, and a type that cannot be imported is a
  type that gets retyped. `FormPage.tsx` already documents this exact unreachability for
  a sibling case (`urlParams`), which is how the third copy came to exist.
- `FormPage.tsx` imports it and deletes the local declaration.
- `FormPage.fieldSpec.test.ts` is the pin.
- One changeset.

⚠️ **Scope note for review.** The card fenced
`packages/app-shell/src/views/metadata-admin/form-spec.ts` as a read-only reuse target
and it is **untouched** — confirmed, it is not in this diff. But reuse needed
reachability, so this PR does add two additive `export type` lines to app-shell's
barrels (`views/metadata-admin/index.ts` and `src/index.ts`). That is beyond the letter
of the declared file surface. Flagging rather than burying it: if the reviewer would
rather not widen app-shell's public type surface, the alternative is a subpath export or
moving the type to a shared package, both larger than this card.

## The pin, and proof that it bites

The pin does not name the console's type — it reads it **back out of the exported
`buildSections` signature**, walking spec → sections → fields → the non-string arm. So it
follows whatever `FormPage.tsx` actually uses in that position and cannot be satisfied by
a decoy:

```ts
type ConsoleFormViewSpec = Parameters( typeof buildSections )[0];
type ConsoleSectionSpec = NonNullable( ConsoleFormViewSpec['sections'] )[number];
type ConsoleFieldSpec = Exclude( ConsoleSectionSpec['fields'][number], string );

const oneContract: Assert( Equal( ConsoleFieldSpec, FormFieldSpec ) ) = true;
```

(Written with parens above because the write path eats angle brackets; the file uses real
generics.)

**Liveness probe — a type assertion no project compiles is a phantom check.** Rather than
flip the assertion to a trivially false thing, I simulated the actual regression: dropped
the shared import and re-inlined the nine-key local `interface FormFieldSpec`, exactly as
a future agent would. `FormPage.tsx` still compiles on its own, so the redness is the pin
and nothing else:

```
BEFORE  import-line count : 1     local-decl count : 0
MUTATE
AFTER   import-line count : 0     local-decl count : 1
        apps/console/src/components/FormPage.tsx | 13 ++++++++++++-
        1 file changed, 12 insertions(+), 1 deletion(-)

src/components/FormPage.fieldSpec.test.ts(81,29): error TS2344: Type 'false' does not satisfy the constraint 'true'.
src/components/FormPage.fieldSpec.test.ts(81,9):  error TS2322: Type 'true' is not assignable to type 'false'.
src/components/FormPage.fieldSpec.test.ts(109,5): error TS2353: Object literal may only specify known properties, and 'type' does not exist in type 'FormFieldSpec'.
src/components/FormPage.fieldSpec.test.ts(165,17): error TS2353: Object literal may only specify known properties, and 'type' does not exist in type 'FormFieldSpec'.
Exit status 2
```

Line 81 is the pin. Note the TS2353 pair: a re-inlined copy immediately re-creates
#5040's exact symptom, and the pin reports it in #5040's own words. Restored via
`trap ... EXIT INT TERM`; `git status --porcelain` empty afterwards and both anchored
counts back to 1 / 0.

Three further controls stop the pin being vacuous, and they compile on **every** run
rather than being a one-time ritual:

- the removed nine-key shape is pinned **not** equal to the shared type, so the `Equal`
  helper is proven to still discriminate;
- `RenderableField` is pinned **not** equal to it either, so the honoured-row and
  authored-document types cannot be quietly collapsed again;
- an undeclared key is still rejected (`@ts-expect-error`), so the import did not smuggle
  in an index signature or `any` — the failure mode a widening reaches for first.

`check-type-check-coverage` independently confirms a project really compiles this file:
`41/41 packages compile their tests, 0 with a narrow type-assertion project`.

## Gate verdicts — exit codes captured before any pipe, each gate's own verdict line quoted

All run at `5536bd387`, the final commit; the probe restored the tree to that exact sha
before this list was taken.

| gate | verdict line | exit |
| --- | --- | --- |
| `@object-ui/console` `type-check` | `os-verify-lock: VERDICT command-exit 0 · held the lock 21s` | 0 |
| `@object-ui/app-shell` `type-check` | (`tsc --noEmit` then `tsc -p tsconfig.test.json`, no output) | 0 |
| `@object-ui/app-shell` `build` | (`tsc`, no output) | 0 |
| `@object-ui/console` `lint` | `✖ 200 problems (0 errors, 200 warnings)` | 0 |
| `@object-ui/app-shell` `lint` | `✖ 2509 problems (0 errors, 2509 warnings)` | 0 |
| `vitest run` (repo root cwd) | `Test Files  202 passed (202)` / `Tests  2191 passed \| 1 skipped (2192)` | 0 |
| `vitest` — the new pin file, verbose | `Test Files  1 passed (1)` / `Tests  2 passed (2)` | 0 |
| `check-control-bytes` | `✅ check-control-bytes: OK (scanned 4647 tracked text file(s); skipped 85 binary).` | 0 |
| `check-changeset-presence` | `✅ 3 source file(s) of 2 released package(s) changed, and this change declares 1 changeset(s)` | 0 |
| `check-changeset-no-major` | `✅ No changeset declares a 'major' bump.` | 0 |
| `check-changeset-fixed` | `✅ All workspace packages are in the changeset fixed group.` | 0 |
| `check-type-check-coverage` | `✅ type-check coverage: 45/46 via 'type-check' … 41/41 packages compile their tests` | 0 |
| `check-lint-coverage` | `✅ lint coverage: 46/46 packages linted, 0 with outstanding errors (0 total).` | 0 |
| `@object-ui/console` `build` | (`tsc`, `vite build`, `tsc -p tsconfig.plugin.json`) | 0 |
| `check-eager-closure-budget` | `✅ Console eager closure is 3784.9 KB gzipped across 52 of 508 chunks (budget: 3867.2 KB, headroom: 82.3 KB).` | 0 |

Two notes on how that list was built rather than taken on trust:

- **The dispatched gate list was treated as a clue, not a spec.** I re-derived it from
  the CI workflows against my actual diff, which added four gates the dispatch did not
  name: `check-type-check-coverage`, `check-lint-coverage`, `check-eager-closure-budget`,
  and the console `build` the last of those needs. `check-eager-closure-budget` was **red
  before the build** — `No eager-closure report … This is a broken gauge, not a passing
  budget` — so rather than argue that a type-only import must be erased, I built the
  console and read the real number.
- **The root `vitest` reporter names only failing files**, so a green run is not by
  itself evidence that the new pin file ran at all — the same shape as a `--filter` that
  matches nothing. Re-run alone with `--reporter=verbose`, which names it under the
  `@object-ui/console` project with both tests passing.

Declared narrowing: `vitest` was scoped to `apps/console/src/components/` and
`packages/app-shell/src/views/metadata-admin/` rather than the whole repo. Evidence it
cannot hide a failure: the app-shell half of this diff is two `export type` lines, which
emit no JavaScript at all, so no module outside those two paths can observe a runtime
difference; the console half is an `import type` plus a deleted `interface`, both fully
erased. CI runs the full farm regardless.

## Out of scope, filed separately

Three findings from the same read, all unassigned, none fixed here:

- #5594 — this same console renderer never evaluates `visibleWhen`/`visibleOn` at all.
  objectui#2212 recorded that symptom and PR #2214 fixed it in the **other** form chain
  (`plugin-form` `sectionFields.ts` plus `components` `renderers/form/form.tsx`);
  `FormPage.tsx` is not on that chain, so the fix never reached it. User-reachable.
- #5595 — `buildSections` drops the field-level `maxLength` override while its own
  docstring promises overrides win. Pre-existing and unchanged by this PR, but newly
  *expressible* because the shared type declares the key. The new test records the
  current answer explicitly rather than assuming it.
- #5596 — the same drift class one level up: `FormViewSpec` and `FormSectionSpec` are each
  hand-declared twice, and unlike the field spec those two have **already** drifted in
  both directions. `finding`, not queued: converging the containers is a real
  architectural call, not a mechanical one.

### CODE REVIEW

**Comment by os-sales** [comment]
## PM review — ACCEPT (card #5542)

**Gates.** 22 named check runs read individually for `completed` + `success`: 19 success, 3 `skipped` — `Test (coverage)`, the unexpanded `Test (coverage shard …/4)` matrix placeholder, and `dependabot`. Those three are always-skipped no-ops in this repo's set, not missing coverage. All four real shards, `Type Check`, `Lint`, `Build & E2E`, `Build Docs`, `Bundle Analysis`, `Doc Snippet Type Check`, `Doc Component Type Check`, both Changeset checks and `Changeset Fixed Group Check` are green on the head commit.

**Merits.**

- The third `FormFieldSpec` at `apps/console/src/components/FormPage.tsx:278` carries exactly **9 keys** (`field, label, placeholder, helpText, required, readonly, hidden, colSpan, widget`) against the shared `form-spec.ts:26` declaration's 26. The dev's count is correct; my own earlier count of 10 was wrong — my read window overran the interface block into the declaration that follows and picked up its `name`. Correcting that here so the record is right.
- `RenderableField` immediately follows and is the genuine narrower renderer type, so the duplication being removed is the redundant one, not the intentional narrowing.

**PM fence error, disclosed.** I fenced `form-spec.ts` as a read-only reuse target. `FormFieldSpec` there is reachable from neither `views/metadata-admin/index.ts` nor `src/index.ts`, so the target was not in fact reusable and the fence was unsatisfiable as written. The two additive `export type` lines in this diff are a consequence of my fence, not scope creep by the implementer.

**Clause ② — not tripped.** The two added lines are type-only: no contract accept/reject behaviour changes, no runtime surface widens, and the barrel already re-exports from `views/metadata-admin/index.js` at `src/index.ts:301,311`. This does not require the contract-review tier.

**Flagged to the maintainer.** Exporting these two types from the app barrel is a boundary call I made, not one the card asked for. It is cheaply reversible later — either a subpath export, or moving the type into a shared package — if you would rather the console barrel stay closed.

---
_Generated by [Claude Code](https://claude.ai/code)_
